import requests
import base64
import uuid
import re

class GitHubAPIError(Exception):
    pass

def _parse_repo_url(repo_url: str) -> str:
    """Extract owner/repo from a GitHub URL."""
    # handle https://github.com/owner/repo or https://github.com/owner/repo.git
    clean_url = repo_url.strip().rstrip("/")
    if clean_url.endswith(".git"):
        clean_url = clean_url[:-4]
    
    match = re.search(r"github\.com/([^/]+)/([^/]+)", clean_url)
    if not match:
        raise ValueError("Invalid GitHub URL format. Must be https://github.com/owner/repo")
    
    return f"{match.group(1)}/{match.group(2)}"

def create_github_pr(repo_url: str, file_path: str, new_code: str, token: str) -> str:
    """
    Creates a new branch, updates the file, and opens a Pull Request on GitHub.
    Returns the PR URL.
    """
    repo_full_name = _parse_repo_url(repo_url)
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }
    
    base_api = f"https://api.github.com/repos/{repo_full_name}"

    # 1. Get default branch
    repo_info_resp = requests.get(base_api, headers=headers)
    if not repo_info_resp.ok:
        raise GitHubAPIError(f"Failed to fetch repo info: {repo_info_resp.json().get('message')}")
    default_branch = repo_info_resp.json().get("default_branch", "main")

    # 2. Get latest commit SHA of default branch
    ref_resp = requests.get(f"{base_api}/git/ref/heads/{default_branch}", headers=headers)
    if not ref_resp.ok:
        raise GitHubAPIError(f"Failed to get default branch ref: {ref_resp.json().get('message')}")
    latest_sha = ref_resp.json()["object"]["sha"]

    # 3. Create a new branch
    new_branch_name = f"codedebtai-fix-{uuid.uuid4().hex[:8]}"
    create_ref_resp = requests.post(
        f"{base_api}/git/refs",
        headers=headers,
        json={"ref": f"refs/heads/{new_branch_name}", "sha": latest_sha}
    )
    if not create_ref_resp.ok:
        raise GitHubAPIError(f"Failed to create new branch: {create_ref_resp.json().get('message')}")

    # 4. Get the file's current SHA (needed for updating an existing file)
    # file_path in UI is relative, but ensure it doesn't have leading slashes
    clean_file_path = file_path.lstrip("/\\")
    
    file_info_resp = requests.get(
        f"{base_api}/contents/{clean_file_path}?ref={new_branch_name}",
        headers=headers
    )
    
    file_sha = None
    if file_info_resp.ok:
        file_sha = file_info_resp.json().get("sha")

    # 5. Commit the new code to the new branch
    # GitHub API requires content to be base64 encoded
    encoded_content = base64.b64encode(new_code.encode("utf-8")).decode("utf-8")
    
    commit_payload = {
        "message": f"CodeDebtAI: Refactor {clean_file_path}",
        "content": encoded_content,
        "branch": new_branch_name
    }
    if file_sha:
        commit_payload["sha"] = file_sha

    update_resp = requests.put(
        f"{base_api}/contents/{clean_file_path}",
        headers=headers,
        json=commit_payload
    )
    if not update_resp.ok:
        raise GitHubAPIError(f"Failed to commit file: {update_resp.json().get('message')}")

    # 6. Open a Pull Request
    pr_payload = {
        "title": f"CodeDebtAI Refactoring for {clean_file_path}",
        "body": "This Pull Request was automatically generated by CodeDebtAI to improve code health and reduce technical debt.",
        "head": new_branch_name,
        "base": default_branch
    }
    pr_resp = requests.post(
        f"{base_api}/pulls",
        headers=headers,
        json=pr_payload
    )
    
    if not pr_resp.ok:
        raise GitHubAPIError(f"Failed to create Pull Request: {pr_resp.json().get('message')}")

    return pr_resp.json().get("html_url")
